version: '3.9'
services:
  backend:
    build: ./backend
    container_name: mnist-backend
    ports:
      - "3000:3000"
  
  frontend:
    build: ./frontend
    container_name: mnist-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
